[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[packages]
boto3 = "*"
breach-buster-redux = "*"
colorama = "*"
coreapi = "*"
dj-database-url = "*"
django = "<3"
django-anymail = "*"
django-auxilium = "*"
django-bleach = "<5"
django-configurations = "*"
django-cors-headers = "*"
django-debug-toolbar = "*"
django-dirtyfields = "*"
django-extensions = "*"
django-modeltranslation = "*"
django-pipeline = "*"
django-rosetta = "*"
django-storages = "*"
django-tinymce4-lite = "*"
django-url-filter = "*"
djangorestframework = "*"
drf-yasg = "*"
gunicorn = "*"
packaging = "*"
pillow = "*"
psycopg2-binary = ">=2.8,<2.9" # see https://stackoverflow.com/questions/68024060/assertionerror-database-connection-isnt-set-to-utc
requests = "*"
structlog = "*"
whitenoise = "*"

[dev-packages]
black = "==19.3b0"
django-extensions = "*"
flake8 = "*"
flake8-bugbear = "*"
importanize = "*"
mccabe = "*"
mypy = "*"
pdbpp = "*"
pre-commit = "*"
pre-commit-hooks = "*"
ptpython = "*"
watchdog = "*"
werkzeug = "*"

[requires]
python_version = "3.8"
